### ISSUE TITLE
IllegalStateException: Length field has not been set in constructor for UnknownMessage after parse.

### ISSUE THREAD

**Issue by avlo** [pokkst/litecoinj#3]
anyone else seeing below stacktrace when constructing `WalletAppKit` using `org.litecoin.test (TestNet3Params)` and have a proper workaround (that doesn't involve a try/catch hack)?

the exception does not cause application to crash, but rather is thrown over and over- ad infinitum.  strangely at one point, the below exception stopped for several hours- then reappeared.  

it appears to be specifically recurring about failed de-serialization of this message (and nothing else):

`5c0100000015f7675900000000ffffff7f00000000ffffff7ffeffff7f0000000000ffffff7f00ffffff7f002f555247454e543a20416c657274206b657920636f6d70726f6d697365642c2075706772616465207265717569726564004630440220405f7e7572b176f3316d4e12deab75ad4ff978844f7a7bcd5ed06f6aa094eb6602207880fcc07d0a78e0f46f188d115e04ed4ad48980ea3572cb0e0cb97921048095`

the critical parts of the stacktrace are:
`org.litecoinj.core.BitcoinSerializer : No support for deserializing message with name alert`
and
`java.lang.IllegalStateException: Length field has not been set in constructor for UnknownMessage after parse.`

here's the full stacktrace:

```java
2021-05-04 09:16:13.007  INFO 43756 --- [ioClientManager] org.litecoinj.core.Peer                  : Peer{[104.237.131.138]:19335, version=70015, subVer=/LitecoinCore:0.18.1/, services=1037 (NETWORK, BLOOM, WITNESS, NETWORK_LIMITED), time=2021-05-04 09:16:12, height=1886649}
2021-05-04 09:16:13.010  INFO 43756 --- [ioClientManager] org.litecoinj.core.PeerGroup             : Peer{[104.237.131.138]:19335, version=70015, subVer=/LitecoinCore:0.18.1/, services=1037 (NETWORK, BLOOM, WITNESS, NETWORK_LIMITED), time=2021-05-04 09:16:12, height=1886649}: New peer      (1 connected, 5 pending, 6 max)
2021-05-04 09:16:13.010  INFO 43756 --- [ioClientManager] org.litecoinj.core.Peer                  : Peer{[104.237.131.138]:19335, version=70015, subVer=/LitecoinCore:0.18.1/, services=1037 (NETWORK, BLOOM, WITNESS, NETWORK_LIMITED), time=2021-05-04 09:16:12, height=1886649}: Sending Bloom filter and querying mempool
2021-05-04 09:16:13.012  WARN 43756 --- [ioClientManager] org.litecoinj.core.BitcoinSerializer     : No support for deserializing message with name alert
2021-05-04 09:16:13.018  WARN 43756 --- [ioClientManager] org.litecoinj.core.PeerSocketHandler     : [104.237.131.138]:19335 - 

org.litecoinj.core.ProtocolException: Error deserializing message 5c0100000015f7675900000000ffffff7f00000000ffffff7ffeffff7f0000000000ffffff7f00ffffff7f002f555247454e543a20416c657274206b657920636f6d70726f6d697365642c2075706772616465207265717569726564004630440220405f7e7572b176f3316d4e12deab75ad4ff978844f7a7bcd5ed06f6aa094eb6602207880fcc07d0a78e0f46f188d115e04ed4ad48980ea3572cb0e0cb97921048095

	at org.litecoinj.core.BitcoinSerializer.deserializePayload(BitcoinSerializer.java:212) ~[litecoinj-core-0.2.jar:na]
	at org.litecoinj.core.BitcoinSerializer.deserialize(BitcoinSerializer.java:173) ~[litecoinj-core-0.2.jar:na]
	at org.litecoinj.core.PeerSocketHandler.receiveBytes(PeerSocketHandler.java:157) ~[litecoinj-core-0.2.jar:na]
	at org.litecoinj.net.ConnectionHandler.handleKey(ConnectionHandler.java:238) [litecoinj-core-0.2.jar:na]
	at org.litecoinj.net.NioClientManager.handleKey(NioClientManager.java:86) [litecoinj-core-0.2.jar:na]
	at org.litecoinj.net.NioClientManager.run(NioClientManager.java:122) [litecoinj-core-0.2.jar:na]
	at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:66) [guava-30.1.1-jre.jar:na]
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:117) [guava-30.1.1-jre.jar:na]
	at org.litecoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:50) [litecoinj-core-0.2.jar:na]
	at java.base/java.lang.Thread.run(Thread.java:844) [na:na]
Caused by: java.lang.IllegalStateException: Length field has not been set in constructor for UnknownMessage after parse.
	at com.google.common.base.Preconditions.checkState(Preconditions.java:591) ~[guava-30.1.1-jre.jar:na]
	at org.litecoinj.core.Message.<init>(Message.java:93) ~[litecoinj-core-0.2.jar:na]
	at org.litecoinj.core.Message.<init>(Message.java:101) ~[litecoinj-core-0.2.jar:na]
	at org.litecoinj.core.EmptyMessage.<init>(EmptyMessage.java:41) ~[litecoinj-core-0.2.jar:na]
	at org.litecoinj.core.UnknownMessage.<init>(UnknownMessage.java:28) ~[litecoinj-core-0.2.jar:na]
	at org.litecoinj.core.BitcoinSerializer.makeMessage(BitcoinSerializer.java:260) ~[litecoinj-core-0.2.jar:na]
	at org.litecoinj.core.BitcoinSerializer.deserializePayload(BitcoinSerializer.java:210) ~[litecoinj-core-0.2.jar:na]
	... 9 common frames omitted

2021-05-04 09:16:13.019  INFO 43756 --- [ioClientManager] org.litecoinj.core.PeerGroup             : [104.237.131.138]:19335: Peer died      (0 connected, 5 pending, 6 max)
2021-05-04 09:16:13.019  INFO 43756 --- [eerGroup Thread] org.litecoinj.core.PeerGroup             : Waiting 1000 ms before next connect attempt to [195.201.246.33]:19335
2021-05-04 09:16:13.021  WARN 43756 --- [ioClientManager] org.litecoinj.net.ConnectionHandler      : Error handling SelectionKey: java.lang.IllegalStateException 

java.lang.IllegalStateException: null
	at com.google.common.base.Preconditions.checkState(Preconditions.java:494) ~[guava-30.1.1-jre.jar:na]
	at org.litecoinj.net.ConnectionHandler.handleKey(ConnectionHandler.java:239) ~[litecoinj-core-0.2.jar:na]
	at org.litecoinj.net.NioClientManager.handleKey(NioClientManager.java:86) [litecoinj-core-0.2.jar:na]
	at org.litecoinj.net.NioClientManager.run(NioClientManager.java:122) [litecoinj-core-0.2.jar:na]
	at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:66) [guava-30.1.1-jre.jar:na]
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:117) [guava-30.1.1-jre.jar:na]
	at org.litecoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:50) [litecoinj-core-0.2.jar:na]
	at java.base/java.lang.Thread.run(Thread.java:844) [na:na]

```

**Comment by pokkst** [comment]
This is a non-issue since alerts are no longer used anywhere. bitcoinj removed alert messages recently.

**Comment by lwebbz** [comment]
I'm having the same issue and your solution of removing the existing spv and wallet files doesn't work for me. This means that my litecoinj app will only connect to nodes running Litecoin Core 13.2 since later releases send a final alert message (introduced in Litecoin Core 14.2) which causes litecoinj to throw this exception, killing the connection and earlier versions send regular alert messages which also throws this exception
