### ISSUE TITLE
deserializing  error

### ISSUE THREAD

**Issue by sumanthyalaga** [pokkst/litecoinj#9]
I am trying to develop a wallet application using liteconj library.
When the wallet starts syncing it immediately throws the below error.

```
2023-01-16 14:34:15.134  WARN 9940 --- [ioClientManager] org.bitcoinj.core.BitcoinSerializer      : No support for deserializing message with name alert
2023-01-16 14:34:15.134  INFO 9940 --- [eerGroup Thread] org.bitcoinj.core.PeerGroup              : Waiting 1000 ms before next connect attempt to [77.120.122.116]:9333
2023-01-16 14:34:15.134  WARN 9940 --- [ioClientManager] org.bitcoinj.core.PeerSocketHandler      : [176.126.167.10]:9333 - 

org.bitcoinj.core.ProtocolException: Error deserializing message 5c0100000015f7675900000000ffffff7f00000000ffffff7ffeffff7f0000000000ffffff7f00ffffff7f002f555247454e543a20416c657274206b657920636f6d70726f6d697365642c2075706772616465207265717569726564004630440220405f7e7572b176f3316d4e12deab75ad4ff978844f7a7bcd5ed06f6aa094eb6602207880fcc07d0a78e0f46f188d115e04ed4ad48980ea3572cb0e0cb97921048095

	at org.bitcoinj.core.BitcoinSerializer.deserializePayload(BitcoinSerializer.java:212) ~[litecoinj-0.2.jar:na]
	at org.bitcoinj.core.BitcoinSerializer.deserialize(BitcoinSerializer.java:173) ~[litecoinj-0.2.jar:na]
	at org.bitcoinj.core.PeerSocketHandler.receiveBytes(PeerSocketHandler.java:157) ~[litecoinj-0.2.jar:na]
	at org.bitcoinj.net.ConnectionHandler.handleKey(ConnectionHandler.java:238) ~[litecoinj-0.2.jar:na]
	at org.bitcoinj.net.NioClientManager.handleKey(NioClientManager.java:86) ~[litecoinj-0.2.jar:na]
	at org.bitcoinj.net.NioClientManager.run(NioClientManager.java:122) ~[litecoinj-0.2.jar:na]
	at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:65) ~[guava-30.0-android.jar:na]
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:119) ~[guava-30.0-android.jar:na]
	at org.bitcoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:50) ~[litecoinj-0.2.jar:na]
	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
Caused by: java.lang.IllegalStateException: Length field has not been set in constructor for UnknownMessage after parse.
	at com.google.common.base.Preconditions.checkState(Preconditions.java:592) ~[guava-30.0-android.jar:na]
	at org.bitcoinj.core.Message.<init>(Message.java:93) ~[litecoinj-0.2.jar:na]
	at org.bitcoinj.core.Message.<init>(Message.java:101) ~[litecoinj-0.2.jar:na]
	at org.bitcoinj.core.EmptyMessage.<init>(EmptyMessage.java:41) ~[litecoinj-0.2.jar:na]
	at org.bitcoinj.core.UnknownMessage.<init>(UnknownMessage.java:28) ~[litecoinj-0.2.jar:na]
	at org.bitcoinj.core.BitcoinSerializer.makeMessage(BitcoinSerializer.java:260) ~[litecoinj-0.2.jar:na]
	at org.bitcoinj.core.BitcoinSerializer.deserializePayload(BitcoinSerializer.java:210) ~[litecoinj-0.2.jar:na]
	... 9 common frames omitted

```

**Comment by pokkst** [comment]
That "error" is a non-issue.
